import { supabase } from './supabase'
export type DistrictProfile={districtId:string;districtName:string;planName:string;duration:string;subText:string;totalGoals:number;mission:string;vision:string;logo:string|null;planImage:string|null}
export type Goal={id:string;name:string;description:string;totalIndicators:number;totalInitiatives:number}
export type Indicator={id:string;name:string;description:string;value:string;numeric:number|null;previous:number|null;variance:number|null;year:string;nature:'Positive'|'Negative';isPercent:boolean}
export type SubInitiative={name:string;done:number;inProgress:number;notStarted:number}
export type Initiative={id:string;name:string;description:string;done:number;inProgress:number;notStarted:number;completion:number;start?:string;end?:string;subInitiatives:SubInitiative[]}
export async function getProfile():Promise<DistrictProfile>{const {data,error}=await supabase.from('District_Profile').select('*').limit(1);if(error)throw error;const d=data?.[0];if(!d)throw new Error('District profile not found');return{districtId:d['District ID'],districtName:d['School District Name'],planName:d['Strategic Plan Name']||'',duration:d['Strategic Plan Duration']||'',subText:d['Sub Text']||'',totalGoals:Number(d['Total Goals']||0),mission:d['Mission Statement']||'',vision:d['Vision Statement']||'',logo:d['District Logo'],planImage:d['Strategic Plan Image']}}
export async function getGoals():Promise<Goal[]>{const{data,error}=await supabase.from('Goal_master').select('*').eq('Role','All').order('Goal ID');if(error)throw error;return(data||[]).map(d=>({id:d['Goal ID'],name:d['Goal Name']||d['Goal ID'],description:d['Goal Description']||'',totalIndicators:Number(d['Total Indicators']||0),totalInitiatives:Number(d['Total Initiatives']||0)}))}
export async function getIndicators(goalId:string):Promise<Indicator[]>{const{data:master,error:me}=await supabase.from('Indicator_master').select('*').eq('Goal ID',goalId).eq('Role','All').order('Indicator ID');if(me)throw me;const{data,error}=await supabase.rpc('fn_indicator_key_values',{p_goal_id:goalId,p_school:null});if(error)throw error;
 const allowed=new Set((master||[]).map(m=>m['Indicator ID']));
 const unexpected=(data||[]).filter((r:any)=>!allowed.has(r.indicator_id));if(unexpected.length)console.warn('Ignoring indicator rows not present in Indicator_master',unexpected);
 return(master||[]).map(m=>{const r=(data||[]).find((x:any)=>x.indicator_id===m['Indicator ID']);return{id:m['Indicator ID'],name:m['Indicator Name']||m['Indicator ID'],description:m['Indicator Description']||'',value:r?.value_3_display??'—',numeric:r?.value_3_numeric==null?null:Number(r.value_3_numeric),previous:r?.previous_year_value_3_numeric==null?null:Number(r.previous_year_value_3_numeric),variance:r?.ly_variance_numeric==null?null:Number(r.ly_variance_numeric),year:r?.school_year??'—',nature:m['KPI Nature']==='Negative'?'Negative':'Positive',isPercent:typeof r?.value_3_display==='string'&&r.value_3_display.includes('%')}})}
export async function getIndicatorHistory(indicatorId:string){const{data,error}=await supabase.rpc('fn_indicator_year_history',{p_indicator_id:indicatorId,p_school:null});if(error)throw error;return data||[]}
export async function getStudentGroups(indicatorId:string,schoolYear:string){const{data,error}=await supabase.rpc('fn_indicator_student_groups',{p_indicator_id:indicatorId,p_school_year:schoolYear,p_school:null});if(error)throw error;return data||[]}
export async function getInitiatives(goalId:string):Promise<Initiative[]>{const{data:masters,error:me}=await supabase.from('Initiative_master').select('*').eq('Goal ID',goalId).eq('Role','All').order('Initiative ID');if(me)throw me;const{data:rows,error}=await supabase.from('Initiative_Data').select('*').eq('Goal ID',goalId).eq('Role','All');if(error)throw error;
 const allowed=new Set((masters||[]).map(m=>m['Initiative ID']));
 const validRows=(rows||[]).filter(r=>allowed.has(r['Initiative ID']));
 return(masters||[]).map(m=>{const rr=validRows.filter(r=>r['Initiative ID']===m['Initiative ID']);const counts=(a:any[])=>({done:a.filter(x=>x.Status==='Done').length,inProgress:a.filter(x=>x.Status==='In Progress').length,notStarted:a.filter(x=>x.Status==='Not Yet Started').length});const c=counts(rr),total=rr.length;const names=[...new Set(rr.map(r=>r['Sub Initiative Name']).filter(Boolean))] as string[];return{id:m['Initiative ID'],name:m['Initiative Name']||m['Initiative ID'],description:m['Initiative Description']||'',done:c.done,inProgress:c.inProgress,notStarted:c.notStarted,completion:total?100*c.done/total:0,start:rr.map(r=>r['Start Date']).filter(Boolean).sort()[0],end:rr.map(r=>r['End Date']).filter(Boolean).sort().at(-1),subInitiatives:names.map(name=>{const x=counts(rr.filter(r=>r['Sub Initiative Name']===name)),t=x.done+x.inProgress+x.notStarted||1;return{name,done:100*x.done/t,inProgress:100*x.inProgress/t,notStarted:100*x.notStarted/t}})}})}
