const goals=[
['Goal 1','Culture of Excellence','Ensure high levels of academic achievement for all students through effective instruction, supportive learning environments, and continuous improvement.',51,26,23,'M-STEP ELA','40%','M-STEP Math','34%','https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=80'],
['Goal 2','Support for All Students','Provide a safe, inclusive, and supportive environment that meets the academic, social, and emotional needs of every student.',60,20,20,'Chronic Absenteeism','18%','Students with Disabilities','28%','https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80'],
['Goal 3','Engaged Community','Foster strong family, community, and industry partnerships to support student learning and well-being.',40,35,25,'Graduation Rate','87%','College & Career Readiness','72%','https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=80'],
['Goal 4','Operational Excellence','Ensure responsible stewardship of resources to support a safe, efficient, and sustainable learning environment.',50,25,25,'Average SAT Score','912.8','Per Pupil Spending','$12,580','https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=900&q=80'],
['Goal 5','Future Ready Learning','Build innovative learning experiences that prepare every student for future opportunities.',35,45,20,'Career Readiness','76%','Advanced Coursework','68%','https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80'],
['Goal 6','Student Wellbeing','Strengthen belonging, wellness, and supports that help students thrive.',55,30,15,'Attendance','93%','Belonging','81%','https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=80']];
let page=0;function perPage(){return innerWidth<=650?1:innerWidth<=1000?2:4}
function render(){const n=perPage(),pages=Math.ceil(goals.length/n);page=Math.max(0,Math.min(page,pages-1));const start=page*n;document.getElementById('counter').textContent=(start+1)+'–'+Math.min(start+n,goals.length)+' of '+goals.length+' Goals';document.getElementById('goals').innerHTML=goals.slice(start,start+n).map(g=>'<article class="goal"><div class="pic" style="background-image:url('+g[10]+')"></div><div class="body"><small>'+g[0]+'</small><h3>'+g[1]+'</h3><p class="desc">'+g[2]+'</p><div class="row"><span>Key Initiatives</span><a>View All →</a></div><div class="stack"><span class="done" style="width:'+g[3]+'%">'+g[3]+'%</span><span class="progress" style="width:'+g[4]+'%">'+g[4]+'%</span><span class="not" style="width:'+g[5]+'%">'+g[5]+'%</span></div><div class="legend"><span><i class="done"></i>Done</span><span><i class="progress"></i>In Progress</span><span><i class="not"></i>Not Yet Started</span></div><div class="row"><span>Key Indicators</span><a>View All →</a></div><div class="kpis"><div class="kpi"><span>'+g[6]+'</span><b>'+g[7]+'</b></div><div class="kpi"><span>'+g[8]+'</span><b>'+g[9]+'</b></div></div></div></article>').join('');document.getElementById('dots').innerHTML=Array.from({length:pages},(_,i)=>'<i class="'+(i===page?'on':'')+'"></i>').join('')}
function move(d){page+=d;render()}addEventListener('resize',()=>{page=0;render()});render();