const goals=[
['Goal 1','Culture of Excellence','Ensure high levels of academic achievement for all students through effective instruction, supportive learning environments, and continuous improvement.',51,26,23,[['M-STEP ELA','40%','+2.4%'],['M-STEP Math','34%','-1.2%'],['Attendance','93%','+0.8%'],['Graduation Rate','87%','+1.5%']],'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=80'],
['Goal 2','Equitable Opportunities & Outcomes','Provide a safe, inclusive, and supportive environment that meets the academic, social, and emotional needs of every student.',60,20,20,[['Chronic Absenteeism','18%','-2.0%'],['Student Growth','72%','+3.1%'],['ELA Proficiency','44%','+1.3%'],['Math Proficiency','39%','-0.6%']],'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80'],
['Goal 3','Whole-Child Environments','Foster strong family, community, and industry partnerships to support student learning and well-being.',40,35,25,[['Graduation Rate','87%','+1.8%'],['Attendance','92%','+0.7%'],['Belonging','81%','+2.2%'],['Discipline','6%','-0.9%']],'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=80'],
['Goal 4','High Impact, Diverse Staff','Secure and retain dedicated professionals committed to the academic success of all students.',50,25,25,[['Retention','91%','+1.0%'],['Vacancies','4%','-1.1%'],['Diversity','38%','+2.0%'],['PD Completion','96%','+3.0%']],'https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=900&q=80'],
['Goal 5','Future Ready Learning','Build innovative learning experiences that prepare every student for future opportunities.',35,45,20,[['Career Ready','76%','+4.0%'],['Advanced Courses','68%','+2.0%'],['CTE','55%','+3.0%'],['Dual Enrollment','22%','+1.0%']],'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80'],
['Goal 6','Student Wellbeing','Strengthen belonging, wellness, and supports that help students thrive.',55,30,15,[['Attendance','93%','+1.0%'],['Belonging','81%','+2.0%'],['Counseling','74%','+4.0%'],['Incidents','5%','-1.0%']],'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=80']];
document.getElementById('welcomeGoals').innerHTML=goals.slice(0,4).map(g=>'<article class="welcomeGoal" title="'+g[2]+'"><b>'+g[1]+'</b><p>'+g[2]+'</p></article>').join('');
let page=0;function perPage(){return innerWidth<=650?1:innerWidth<=1000?2:4}
function render(){const n=perPage(),pages=Math.ceil(goals.length/n);page=Math.max(0,Math.min(page,pages-1));const start=page*n;document.getElementById('counter').textContent=(start+1)+'–'+Math.min(start+n,goals.length)+' of '+goals.length+' Goals';document.getElementById('goals').innerHTML=goals.slice(start,start+n).map(g=>'<article class="goal"><div class="pic" style="background-image:url('+g[7]+')"></div><div class="body"><small>'+g[0]+'</small><h3>'+g[1]+'</h3><p class="desc" title="'+g[2]+'">'+g[2]+'</p><div class="row initiativeRow"><span>Key Initiatives</span><a>View All →</a></div><div class="stack"><span class="done" style="width:'+g[3]+'%">'+g[3]+'%</span><span class="progress" style="width:'+g[4]+'%">'+g[4]+'%</span><span class="not" style="width:'+g[5]+'%">'+g[5]+'%</span></div><div class="legend"><span><i class="done"></i>Done</span><span><i class="progress"></i>In Progress</span><span><i class="not"></i>Not Yet Started</span></div><div class="row"><span>Key Indicators</span><a>View All →</a></div><div class="kpis">'+g[6].map(k=>'<div class="kpi"><span>'+k[0]+'</span><b>'+k[1]+'</b><span class="variance '+(k[2][0]=='+'?'positive':'negative')+'"><span class="trend">'+(k[2][0]=='+'?'↗':'↘')+'</span>'+k[2]+'</span></div>').join('')+'</div></div></article>').join('');document.getElementById('dots').innerHTML=Array.from({length:pages},(_,i)=>'<i class="'+(i===page?'on':'')+'"></i>').join('')}
function move(d){page+=d;render()}function closePanels(){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('open'));document.getElementById('scrim').classList.remove('on')}function openPanel(id){closePanels();document.getElementById(id).classList.add('open');document.getElementById('scrim').classList.add('on')}function toggleNav(){document.getElementById('navPanel').classList.contains('open')?closePanels():openPanel('navPanel')}function toggleFilter(){document.getElementById('filterPanel').classList.contains('open')?closePanels():openPanel('filterPanel')}function toggleHelp(){document.getElementById('helpPanel').classList.contains('open')?closePanels():openPanel('helpPanel')}addEventListener('resize',()=>{page=0;render()});render();