import {FormEvent,useEffect,useState} from 'react';
import {BarChart3,Building2,Download,FileSpreadsheet,Home,LogOut,Settings2,Upload} from 'lucide-react';
import {apiDelete,apiGet,apiPost,apiPut} from '../../lib/api';

type Section='home'|'plan'|'indicators'|'initiatives';
type SigninMethod='Userbased'|'Google'|'Microsoft';
type Profile={districtName:string;planName:string;duration:string;mission:string;vision:string;goals:number;logo:string;signinMethod:SigninMethod;googleClientId:string;googleAuthId:string;microsoftClientId:string;microsoftTenantId:string;microsoftAuthId:string};

const menu=[
  {id:'home' as Section,label:'Home',icon:Home},
  {id:'plan' as Section,label:'Strategic Plan Configuration',icon:Settings2},
  {id:'indicators' as Section,label:'Indicator Configuration',icon:BarChart3},
  {id:'initiatives' as Section,label:'Initiative Configuration',icon:FileSpreadsheet},
];

export function SuperAdminPage(){
 const[authenticated,setAuthenticated]=useState(()=>sessionStorage.getItem('strategic_superadmin')==='true');
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[saveMessage,setSaveMessage]=useState('');
 const[section,setSection]=useState<Section>('home');
 const[googleSecret,setGoogleSecret]=useState('');const[microsoftSecret,setMicrosoftSecret]=useState('');
 const[profile,setProfile]=useState<Profile>({districtName:'',planName:'',duration:'',mission:'',vision:'',goals:0,logo:'',signinMethod:'Userbased',googleClientId:'',googleAuthId:'',microsoftClientId:'',microsoftTenantId:'',microsoftAuthId:''});
 const[indicatorPage,setIndicatorPage]=useState(1);const indicatorPageSize=20;const[initiativePage,setInitiativePage]=useState(1);const initiativePageSize=20;const[pendingDeleteGoals,setPendingDeleteGoals]=useState<any[]>([]);const[toast,setToast]=useState<{type:'success'|'error'|'warning',text:string}|null>(null);const[existingGoalCount,setExistingGoalCount]=useState(0);
 const[goals,setGoals]=useState<any[]>([]);const[indicators,setIndicators]=useState<any[]>([]);const[initiatives,setInitiatives]=useState<any[]>([]);const[indicatorCount,setIndicatorCount]=useState(0);const[initiativeCount,setInitiativeCount]=useState(0);

 useEffect(()=>{if(!authenticated)return;const token=sessionStorage.getItem('strategic_superadmin_token');if(!token)return;(async()=>{try{const x=await apiGet<any>('/api/v1/superadmin/configuration?token='+encodeURIComponent(token));const p=x.profile||{};setProfile({districtName:p['School District Name']||'',planName:p['Strategic Plan Name']||'',duration:p['Strategic Plan Duration']||'',mission:p['Mission Statement']||'',vision:p['Vision Statement']||'',goals:Number(p['Total Goals']||0),logo:p['District Logo']||'',signinMethod:(p['Admin Signin Method']||'Userbased') as SigninMethod,googleClientId:p['Google Client ID']||'',googleAuthId:p['Google Auth ID']||'',microsoftClientId:p['Microsoft Client ID']||'',microsoftTenantId:p['Microsoft Tenant ID']||'',microsoftAuthId:p['Microsoft Auth ID']||''});setGoals(x.goals||[]);setExistingGoalCount((x.goals||[]).length);setIndicators(x.indicators||[]);setInitiatives(x.initiatives||[]);setIndicatorCount(x.indicatorCount||0);setInitiativeCount(x.initiativeCount||0)}catch{logout()}})()},[authenticated]);

 async function login(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{const row=await apiPost<any>('/api/v1/superadmin/login',{email:email.trim(),password});sessionStorage.setItem('strategic_superadmin','true');sessionStorage.setItem('strategic_superadmin_token',row.token);setAuthenticated(true);setPassword('')}catch{setError('Sign in failed. Please check your email and password.')}finally{setBusy(false)}}
 function logout(){sessionStorage.removeItem('strategic_superadmin');sessionStorage.removeItem('strategic_superadmin_token');setAuthenticated(false)}
 if(!authenticated)return <main className="superAdminLogin"><form className="superAdminLoginCard" onSubmit={login}>
  <img src="/k12matrix-logo.svg" alt="K12Matrix"/><small className="superAdminAccessLabel">SUPER ADMIN ACCESS</small><h1>Sign In</h1><p>Manage district strategic plan configuration and reporting data.</p>
  <label>Email</label><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter SuperAdmin email"/>
  <label>Password</label><input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/>
  {error&&<div className="superAdminError">{error}</div>}<button disabled={busy}>{busy?'Signing in…':'Sign In'}</button>
 </form></main>;

 function notify(type:'success'|'error'|'warning',text:string){setToast({type,text});window.setTimeout(()=>setToast(null),4000)}
 function changeGoalCount(value:number){const count=Math.max(1,Math.min(20,value||1));if(count<existingGoalCount){notify('warning',`There are already ${existingGoalCount} Goals. The Goal count cannot be reduced here. Delete the Goal that is no longer required first.`);setProfile(p=>({...p,goals:Math.max(existingGoalCount,p.goals)}));return}setProfile({...profile,goals:count});setGoals(prev=>{const next=[...prev];while(next.length<count)next.push({'Goal ID':'','Goal Name':'','Goal Description':'','Role':'All'});return next.slice(0,count)})}
 function updateGoal(index:number,key:'Goal Name'|'Goal Description',value:string){setGoals(prev=>prev.map((g,i)=>i===index?{...g,[key]:value}:g))}
 function requestDeleteGoal(index:number){const goal=goals[index];if(!goal)return;if(!goal['Goal ID']){setGoals(prev=>prev.filter((_,i)=>i!==index));setProfile(p=>({...p,goals:Math.max(existingGoalCount,p.goals-1)}));notify('success','Unsaved Goal removed.');return}setPendingDeleteGoals([goal])}
 async function updateDistrictLogo(file:File){if(!file.type.startsWith('image/')){notify('error','Please select an image file.');return}if(file.size>1024*1024){notify('error','District logo must be 1 MB or smaller.');return}const reader=new FileReader();reader.onload=async()=>{const logo=String(reader.result||'');const token=sessionStorage.getItem('strategic_superadmin_token');if(!token)return;setBusy(true);try{await apiPut('/api/v1/superadmin/logo',{token,logo});setProfile(p=>({...p,logo}));notify('success','District logo updated successfully.')}catch(e){notify('error',e instanceof Error?e.message:'Logo update failed.')}finally{setBusy(false)}};reader.readAsDataURL(file)}
 async function saveConfiguration(){const names=goals.slice(0,profile.goals).map(g=>String(g['Goal Name']||'').trim().toLowerCase());if(names.some(n=>!n)){notify('error','Goal Name is required for every goal.');return}if(new Set(names).size!==names.length){notify('error','Goal names must be distinct. A duplicate Goal Name is already present.');return}if(pendingDeleteGoals.length){notify('warning','Confirm or cancel the pending Goal deletion first.');return}const token=sessionStorage.getItem('strategic_superadmin_token');if(!token){notify('error','Your Super Admin session has expired. Please sign in again.');return}setBusy(true);setSaveMessage('');const payloadGoals=goals.slice(0,profile.goals).map(g=>({'Goal ID':g['Goal ID']||'', 'Goal Name':g['Goal Name']||'', 'Goal Description':g['Goal Description']||''}));try{await apiPut('/api/v1/superadmin/configuration',{token,profile,goals:payloadGoals});if(profile.signinMethod==='Google'&&googleSecret)await apiPut('/api/v1/superadmin/oauth-secrets',{token,googleClientSecret:googleSecret});if(profile.signinMethod==='Microsoft'&&microsoftSecret)await apiPut('/api/v1/superadmin/oauth-secrets',{token,microsoftClientSecret:microsoftSecret});setGoogleSecret('');setMicrosoftSecret('');notify('success','Configuration saved successfully.')}catch(e){notify('error',e instanceof Error?e.message:'Configuration save failed.')}finally{setBusy(false)}}
 
 async function confirmGoalDeletion(){const token=sessionStorage.getItem('strategic_superadmin_token');if(!token)return;setBusy(true);setSaveMessage('');for(const g of pendingDeleteGoals){try{await apiDelete('/api/v1/superadmin/goals/'+encodeURIComponent(g['Goal ID'])+'?token='+encodeURIComponent(token))}catch(e){setBusy(false);notify('error',e instanceof Error?e.message:'Goal deletion failed.');return}}setPendingDeleteGoals([]);setGoals(prev=>prev.filter(g=>g['Goal ID']!==pendingDeleteGoals[0]?.['Goal ID']));setExistingGoalCount(v=>Math.max(0,v-1));setProfile(p=>({...p,goals:Math.max(1,p.goals-1)}));setBusy(false);notify('success','Goal deleted successfully.')}
 function cancelGoalDeletion(){setPendingDeleteGoals([])}
 

 const indicatorColumns=['Goal ID','Goal Name','Indicator ID','Indicator Name','School Year','Category','Student Group','Value 1','Value 2','Value 3','Role','Target 1','Target 2','Target 3','School'];
 const initiativeColumns=['Goal ID','Goal Name','Initiative ID','Initiative Name','Sub Initiative Name','Start Date','End Date','Action Item','Status','Target 1','Target 2','Target 3','School','Stakeholder ID','Role'];
 function csvCell(v:string){return /[",\n\r]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
 function downloadTemplate(kind:'indicator'|'initiative'){const cols=kind==='indicator'?indicatorColumns:initiativeColumns;const blob=new Blob([cols.map(csvCell).join(',')+'\r\n'],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=kind==='indicator'?'indicator_data_template.csv':'initiative_data_template.csv';a.click();URL.revokeObjectURL(a.href);notify('success',(kind==='indicator'?'Indicator':'Initiative')+' CSV template downloaded.')}
 function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row);return rows}
 async function uploadCsv(kind:'indicator'|'initiative',file:File){if(file.size>2*1024*1024){notify('error','CSV file must be 2 MB or smaller.');return}const token=sessionStorage.getItem('strategic_superadmin_token');if(!token){notify('error','Your Super Admin session has expired. Please sign in again.');return}try{const parsed=parseCsv(await file.text());if(parsed.length<2){notify('error','CSV must contain a header and at least one data row.');return}const expected=kind==='indicator'?indicatorColumns:initiativeColumns;const headers=parsed[0].map(x=>x.trim().replace(/^\uFEFF/,''));if(headers.length!==expected.length||expected.some((h,i)=>headers[i]!==h)){notify('error','CSV columns do not match the approved '+kind+' template. Download a fresh template and try again.');return}const rows=parsed.slice(1).map((values,rowIndex)=>{if(values.length!==headers.length)throw new Error('Row '+(rowIndex+2)+' has '+values.length+' columns; expected '+headers.length+'.');return Object.fromEntries(headers.map((h,i)=>[h,values[i]?.trim()??'']))});setBusy(true);const result=await apiPost<any>('/api/v1/superadmin/'+(kind==='indicator'?'indicators':'initiatives')+'/bulk',{token,rows});notify('success',String(result?.result?.rows_processed||rows.length)+' '+kind+' rows uploaded successfully.');const fresh=await apiGet<any>('/api/v1/superadmin/configuration?token='+encodeURIComponent(token));if(kind==='indicator'){setIndicators(fresh.indicators||[]);setIndicatorPage(1)}else{setInitiatives(fresh.initiatives||[]);setInitiativePage(1)}}catch(e){setBusy(false);notify('error',e instanceof Error?e.message:'CSV could not be processed.')}}

 const indicatorPages=Math.max(1,Math.ceil(indicators.length/indicatorPageSize));
 const pagedIndicators=indicators.slice((indicatorPage-1)*indicatorPageSize,indicatorPage*indicatorPageSize);
 const initiativePages=Math.max(1,Math.ceil(initiatives.length/initiativePageSize));
 const pagedInitiatives=initiatives.slice((initiativePage-1)*initiativePageSize,initiativePage*initiativePageSize);
 const data=section==='indicators'?pagedIndicators:pagedInitiatives;
 return <div className="superAdmin">{toast&&<div className={`adminToast ${toast.type}`}>{toast.text}</div>}{pendingDeleteGoals.length>0&&<div className="adminModalBackdrop"><div className="adminConfirmModal" role="dialog" aria-modal="true" aria-labelledby="delete-goal-title"><h3 id="delete-goal-title">Delete Goal?</h3><p>You are about to permanently delete <b>{pendingDeleteGoals[0]?.['Goal Name']}</b>. This action cannot be undone.</p><div className="modalActions"><button type="button" className="modalCancel" onClick={cancelGoalDeletion}>Cancel</button><button type="button" className="modalDelete" onClick={confirmGoalDeletion} disabled={busy}>{busy?'Deleting…':'Delete Goal'}</button></div></div></div>}
  <aside className="superAdminSide"><div className="superAdminBrand"><img src="/k12matrix-logo.svg" alt="K12Matrix"/><div><b>Strategic Plan</b><span>Super Admin</span></div></div>
   <nav>{menu.map(x=>{const Icon=x.icon;return <button key={x.id} className={section===x.id?'active':''} onClick={()=>setSection(x.id)}><Icon size={17}/><span>{x.label}</span></button>})}</nav>
   <button className="superAdminLogout" onClick={logout}><LogOut size={16}/> Sign Out</button>
  </aside>
  <main className="superAdminMain"><header><div><small>SUPER ADMIN</small><h1>{menu.find(x=>x.id===section)?.label}</h1></div><span className="superAdminUser">selva@k12matrix.com</span></header>
   {section==='home'&&<section><div className="adminWelcome"><Building2 size={26}/><div><h2>{profile.districtName||'District'}</h2><p>{profile.planName||'Strategic Plan'} · {profile.duration||'Duration not configured'}</p></div></div><div className="adminStats"><article><span>Goals</span><b>{profile.goals}</b></article><article><span>Indicators</span><b>{indicatorCount}</b></article><article><span>Initiatives</span><b>{initiativeCount}</b></article></div></section>}
   {section==='plan'&&<section className="adminPanel"><h2>District & Strategic Plan</h2><p>Configure the information displayed in the public Strategic Plan Dashboard.</p><div className="adminForm">
    <label>District Name<input value={profile.districtName} onChange={e=>setProfile({...profile,districtName:e.target.value})}/></label>
    <label className="logoField">District Logo<div className="districtLogoInline">{profile.logo&&<img src={profile.logo} alt="District logo preview"/>}<label className="logoUploadBtn">{profile.logo?'Change Logo':'Upload Logo'}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>{const file=e.target.files?.[0];if(file)updateDistrictLogo(file)}}/></label></div></label>
    <label>Strategic Plan Name<input value={profile.planName} onChange={e=>setProfile({...profile,planName:e.target.value})}/></label>
    <label>Strategic Plan Duration<input value={profile.duration} onChange={e=>setProfile({...profile,duration:e.target.value})}/></label>
    <label className="goalCountField">Number of Goals<input className="goalCountInput" type="number" min="1" max="20" value={profile.goals} onChange={e=>changeGoalCount(Number(e.target.value))}/></label>
    <label className="signinField">Admin Signin<select value={profile.signinMethod} onChange={e=>setProfile({...profile,signinMethod:e.target.value as SigninMethod})}><option value="Userbased">Userbased</option><option value="Google">Google</option><option value="Microsoft">Microsoft</option></select></label>
    <label className="wide">Mission Statement<textarea value={profile.mission} onChange={e=>setProfile({...profile,mission:e.target.value})}/></label>
    <label className="wide">Vision Statement<textarea value={profile.vision} onChange={e=>setProfile({...profile,vision:e.target.value})}/></label>
    {profile.signinMethod==='Google'&&<><label>Google Client ID<input value={profile.googleClientId} onChange={e=>setProfile({...profile,googleClientId:e.target.value})}/></label><label>Google Auth ID<input value={profile.googleAuthId} onChange={e=>setProfile({...profile,googleAuthId:e.target.value})}/></label><label>Google Client Secret<input type="password" autoComplete="new-password" value={googleSecret} placeholder="Enter to add or replace secret" onChange={e=>setGoogleSecret(e.target.value)}/></label></>}
    {profile.signinMethod==='Microsoft'&&<><label>Microsoft Client ID<input value={profile.microsoftClientId} onChange={e=>setProfile({...profile,microsoftClientId:e.target.value})}/></label><label>Microsoft Tenant ID<input value={profile.microsoftTenantId} onChange={e=>setProfile({...profile,microsoftTenantId:e.target.value})}/></label><label>Microsoft Auth ID<input value={profile.microsoftAuthId} onChange={e=>setProfile({...profile,microsoftAuthId:e.target.value})}/></label><label>Microsoft Client Secret<input type="password" autoComplete="new-password" value={microsoftSecret} placeholder="Enter to add or replace secret" onChange={e=>setMicrosoftSecret(e.target.value)}/></label></>}
    <div className="adminNotice wide">OAuth client secrets are securely saved through the StrategicPlan API and are never returned to the browser. Leave the secret field blank to keep the existing secret.</div>
   </div><h3>Goal Master</h3><div className="goalEditor">{goals.slice(0,profile.goals).map((g,i)=><article key={g['Goal ID']||i}><div className="goalEditorHead"><b>Goal {i+1}</b><button type="button" className="goalDeleteBtn" onClick={()=>requestDeleteGoal(i)}>Delete</button></div><label>Goal Name<input value={g['Goal Name']||''} onChange={e=>updateGoal(i,'Goal Name',e.target.value)}/></label><label>Goal Description<textarea value={g['Goal Description']||''} onChange={e=>updateGoal(i,'Goal Description',e.target.value)}/></label></article>)}</div><div className="adminNotice">Goal IDs are managed automatically and are not shown here. Increasing the goal count adds another editable Goal section.</div><button className="adminPrimary" disabled={busy} onClick={saveConfiguration}>{busy?'Saving…':'Save Configuration'}</button></section>}
   {(section==='indicators'||section==='initiatives')&&<section className="adminPanel"><div className="adminPanelHead"><div><h2>{section==='indicators'?'Indicator':'Initiative'} Data</h2><p>Review district data and manage bulk updates using the approved CSV template.</p></div><div className="adminActions"><button type="button" onClick={()=>downloadTemplate(section==='indicators'?'indicator':'initiative')}><Download size={15}/> Download Template</button><label className={'adminUpload '+(busy?'disabled':'')}><Upload size={15}/> {busy?'Processing…':'Upload CSV'}<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)uploadCsv(section==='indicators'?'indicator':'initiative',file);e.currentTarget.value=''}}/></label></div></div>
    <div className="adminNotice">Use the downloaded template without changing column names or order. Upload validates the file, IDs and required key fields, then securely inserts new rows or updates matching rows.</div>
    <div className="adminTableWrap"><table><thead><tr>{data[0]&&Object.keys(data[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{data.map((r,i)=><tr key={i}>{Object.keys(r).map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div>
    {section==='indicators'&&<div className="adminPagination"><span>Showing {(indicatorPage-1)*indicatorPageSize+1}–{Math.min(indicatorPage*indicatorPageSize,indicators.length)} of {indicators.length}</span><div><button disabled={indicatorPage===1} onClick={()=>setIndicatorPage(p=>Math.max(1,p-1))}>Previous</button><b>Page {indicatorPage} of {indicatorPages}</b><button disabled={indicatorPage===indicatorPages} onClick={()=>setIndicatorPage(p=>Math.min(indicatorPages,p+1))}>Next</button></div></div>}
    {section==='initiatives'&&<div className="adminPagination"><span>Showing {(initiativePage-1)*initiativePageSize+1}–{Math.min(initiativePage*initiativePageSize,initiatives.length)} of {initiatives.length}</span><div><button disabled={initiativePage===1} onClick={()=>setInitiativePage(p=>Math.max(1,p-1))}>Previous</button><b>Page {initiativePage} of {initiativePages}</b><button disabled={initiativePage===initiativePages} onClick={()=>setInitiativePage(p=>Math.min(initiativePages,p+1))}>Next</button></div></div>}
   </section>}
  </main>
 </div>
}